#!/usr/bin/env bash
# REYOG CAPITAL — IDCloudHost VPS one-click deploy
# Usage (on the VPS, as sudo user):
#   curl -sL https://raw.githubusercontent.com/YOUR_USER/reyog-capital/main/deploy/idcloudhost-deploy.sh | sudo bash
# OR after git clone, run: sudo bash deploy/idcloudhost-deploy.sh
#
# What it does:
#   1. Installs Docker + Compose
#   2. Configures firewall (port 80 open, others closed)
#   3. Builds all containers
#   4. Starts the stack — accessible at http://YOUR_VPS_IP/

set -euo pipefail

REPO_DIR="${REPO_DIR:-$(pwd)}"
VPS_IP="${VPS_IP:-$(curl -s ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')}"

echo "════════════════════════════════════════════════════════════"
echo "  REYOG CAPITAL — IDCloudHost Deploy"
echo "  VPS IP detected: $VPS_IP"
echo "  Repo dir: $REPO_DIR"
echo "════════════════════════════════════════════════════════════"

# ─── Step 1: System update + Docker ───
if ! command -v docker &>/dev/null; then
    echo "[1/6] Installing Docker…"
    apt update -y
    apt install -y curl ca-certificates ufw
    curl -fsSL https://get.docker.com | sh
    # Ensure non-root user (default ubuntu/debian/centos) can use Docker
    if [ -n "${SUDO_USER:-}" ] && [ "$SUDO_USER" != "root" ]; then
        usermod -aG docker "$SUDO_USER"
    fi
else
    echo "[1/6] Docker already installed: $(docker --version)"
fi

# ─── Step 2: Firewall ───
echo "[2/6] Configuring firewall (UFW)…"
ufw allow OpenSSH 2>/dev/null || ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw --force enable
ufw reload

# ─── Step 3: Generate .env if missing ───
cd "$REPO_DIR"
if [ ! -f .env ]; then
    echo "[3/6] Creating .env file…"
    # Random strong password for Postgres
    DB_PW=$(openssl rand -hex 16)
    cat > .env <<EOF
# ─── Auto-generated by idcloudhost-deploy.sh on $(date -u +%FT%TZ) ───
REYOG_DOMAIN=$VPS_IP
NEXT_PUBLIC_API_URL=http://$VPS_IP
NEXT_PUBLIC_WS_URL=ws://$VPS_IP
CORS_ORIGINS=*

DB_USER=arb
DB_PASSWORD=$DB_PW
DB_NAME=ultra_arb
DB_HOST=postgres
DB_PORT=5432
DATABASE_URL=postgresql+asyncpg://arb:$DB_PW@postgres:5432/ultra_arb

REDIS_URL=redis://redis:6379/0

PAPER_TRADE=true

BINANCE_API_KEY=
BINANCE_API_SECRET=
BINANCE_TESTNET=true

BYBIT_API_KEY=
BYBIT_API_SECRET=
BYBIT_TESTNET=true

POLYMARKET_PRIVATE_KEY=
POLYMARKET_SANDBOX=true

FINANCIAL_DATASETS_API_KEY=

MAX_DRAWDOWN_PCT=2.0
MAX_POSITION_PCT=2.5
MAX_CONCURRENT_POSITIONS=5
VOL_BREAKER_MULTIPLIER=3.0
EOF
    chmod 600 .env
    echo "[3/6] .env created with auto-generated DB password (stored in .env, 600 perms)"
else
    echo "[3/6] .env exists — keeping it"
fi

# ─── Step 4: Pre-build sanity check ───
echo "[4/6] Sanity check (free RAM / disk / Docker daemon)…"
free -h | head -2
df -h / | tail -1
docker info &>/dev/null && echo "  Docker daemon: OK"

# ─── Step 5: Build + start ───
echo "[5/6] Building containers (first build ~5-10 min on 4GB VPS)…"
docker compose pull redis postgres nginx 2>&1 | tail -10
docker compose build --parallel 2>&1 | tail -20

echo "[5/6] Starting stack…"
docker compose up -d

# ─── Step 6: Wait for healthchecks ───
echo "[6/6] Waiting for services to be healthy…"
for i in {1..30}; do
    healthy=$(docker compose ps --format json 2>/dev/null | grep -c '"Health":"healthy"' || echo 0)
    if [ "$healthy" -ge 2 ]; then
        echo "  $healthy services healthy."
        break
    fi
    sleep 2
done

docker compose ps
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  ✅ REYOG CAPITAL deployed"
echo ""
echo "  Dashboard:   http://$VPS_IP/"
echo "  API:         http://$VPS_IP/api/health"
echo "  WebSocket:   ws://$VPS_IP/ws/firehose"
echo ""
echo "  Logs:        docker compose logs -f --tail=100"
echo "  Restart:     docker compose restart"
echo "  Stop:        docker compose down"
echo "  Update:      git pull && docker compose up -d --build"
echo "════════════════════════════════════════════════════════════"
