#!/usr/bin/env bash
# REYOG CAPITAL — Oracle Cloud "Always Free" one-command deploy (ARM64/AMD64)
#
# Run ON the fresh Oracle VM (Ubuntu 22.04+ recommended), from the repo root:
#
#   git clone https://github.com/panjivr/ultra-arb.git
#   cd ultra-arb
#   sudo bash deploy/oracle-setup.sh
#
# Result: full REYOG stack on http://<VM_PUBLIC_IP>/ — 24/7, $0 forever.
#
# It:
#   1. Installs Docker + Compose plugin
#   2. Opens port 80 in the VM firewall (Oracle images REJECT it by default via
#      iptables — ufw alone is NOT enough). NOTE: you ALSO must add an Ingress
#      rule for TCP/80 in the OCI Console (VCN > Security List). See docs/07.
#   3. Generates .env (random DB/Redis passwords, PAPER_TRADE=true)
#   4. Builds + starts the ARM-safe free stack (docker-compose.free.yml)

set -euo pipefail

REPO_DIR="${REPO_DIR:-$(pwd)}"
PUBLIC_IP="${PUBLIC_IP:-$(curl -s ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')}"
ARCH="$(uname -m)"

echo "════════════════════════════════════════════════════════════"
echo "  REYOG CAPITAL — Oracle Always Free deploy"
echo "  Public IP : $PUBLIC_IP"
echo "  Arch      : $ARCH"
echo "  Repo      : $REPO_DIR"
echo "════════════════════════════════════════════════════════════"

# ─── 1. Docker ───
if ! command -v docker &>/dev/null; then
    echo "[1/5] Installing Docker…"
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -y
    apt-get install -y curl ca-certificates iptables
    curl -fsSL https://get.docker.com | sh
    if [ -n "${SUDO_USER:-}" ] && [ "$SUDO_USER" != "root" ]; then
        usermod -aG docker "$SUDO_USER" || true
    fi
else
    echo "[1/5] Docker present: $(docker --version)"
fi

# ─── 2. Firewall: open TCP/80 in the VM's iptables ───
# Oracle Ubuntu images ship an INPUT chain that REJECTs everything after SSH.
# Insert an ACCEPT for :80 BEFORE that reject rule, then persist.
echo "[2/5] Opening TCP/80 in VM firewall…"
if ! iptables -C INPUT -p tcp --dport 80 -j ACCEPT 2>/dev/null; then
    iptables -I INPUT 6 -p tcp --dport 80 -j ACCEPT 2>/dev/null \
        || iptables -I INPUT -p tcp --dport 80 -j ACCEPT
fi
# Persist across reboots (best-effort — depends on distro tooling).
if command -v netfilter-persistent &>/dev/null; then
    netfilter-persistent save || true
elif command -v iptables-save &>/dev/null; then
    mkdir -p /etc/iptables && iptables-save > /etc/iptables/rules.v4 || true
fi
echo "  → Reminder: also add Ingress TCP/80 in OCI Console (VCN Security List)."

# ─── 3. .env ───
# Optional: export DOMAIN=pusatbanksoal.online before running to wire a custom
# domain behind Cloudflare (HTTPS). Without it, the raw public IP is used.
cd "$REPO_DIR"
DOMAIN="${DOMAIN:-}"
if [ -n "$DOMAIN" ]; then
    PUB_API="https://$DOMAIN"; PUB_WS="wss://$DOMAIN"
    CORS="https://$DOMAIN,https://www.$DOMAIN"
    REYOG_HOST="$DOMAIN"
    echo "  → Domain mode: $DOMAIN (point it at $PUBLIC_IP via Cloudflare — see docs/08)"
else
    PUB_API="http://$PUBLIC_IP"; PUB_WS="ws://$PUBLIC_IP"; CORS="*"; REYOG_HOST="$PUBLIC_IP"
fi
if [ ! -f .env ]; then
    echo "[3/5] Generating .env…"
    DB_PW=$(openssl rand -hex 16)
    REDIS_PW=$(openssl rand -hex 16)
    cat > .env <<EOF
# ─── Auto-generated by oracle-setup.sh on $(date -u +%FT%TZ) ───
REYOG_DOMAIN=$REYOG_HOST
NEXT_PUBLIC_API_URL=$PUB_API
NEXT_PUBLIC_WS_URL=$PUB_WS
CORS_ORIGINS=$CORS

DB_USER=arb
DB_PASSWORD=$DB_PW
DB_NAME=ultra_arb
DB_HOST=postgres
DB_PORT=5432
DATABASE_URL=postgresql+asyncpg://arb:$DB_PW@postgres:5432/ultra_arb

REDIS_PASSWORD=$REDIS_PW
REDIS_URL=redis://:$REDIS_PW@redis:6379/0

PAPER_TRADE=true

# Free-tier cadence (light on a small VM; still real-time feel)
FIREHOSE_HZ_MS=50
WS_INTERVAL_MS=200

BINANCE_API_KEY=
BINANCE_API_SECRET=
BINANCE_TESTNET=true
BYBIT_API_KEY=
BYBIT_API_SECRET=
BYBIT_TESTNET=true
POLYMARKET_PRIVATE_KEY=
POLYMARKET_SANDBOX=true
FINANCIAL_DATASETS_API_KEY=

MAX_DRAWDOWN_PCT=2.0
MAX_POSITION_PCT=2.5
MAX_CONCURRENT_POSITIONS=5
VOL_BREAKER_MULTIPLIER=3.0
EOF
    chmod 600 .env
    echo "  → .env created (random DB + Redis passwords, 600 perms)."
else
    echo "[3/5] .env exists — keeping it."
fi

# ─── 4. Build + start (ARM-safe free stack) ───
echo "[4/5] Building + starting (first build ~8-15 min on Ampere A1)…"
docker compose -f docker-compose.free.yml pull redis postgres nginx 2>&1 | tail -6 || true
docker compose -f docker-compose.free.yml up -d --build

# ─── 5. Wait + report ───
echo "[5/5] Waiting for healthchecks…"
for i in {1..40}; do
    healthy=$(docker compose -f docker-compose.free.yml ps --format json 2>/dev/null | grep -c '"Health":"healthy"' || echo 0)
    [ "$healthy" -ge 3 ] && { echo "  $healthy services healthy."; break; }
    sleep 3
done

docker compose -f docker-compose.free.yml ps
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  ✅ REYOG CAPITAL live (FREE) — direct: http://$PUBLIC_IP/"
if [ -n "$DOMAIN" ]; then
echo "     Domain  : https://$DOMAIN/  (after Cloudflare DNS — see docs/08)"
fi
echo ""
echo "  API   : http://$PUBLIC_IP/api/health"
echo "  WS    : ws://$PUBLIC_IP/ws/firehose"
echo "  Logs  : docker compose -f docker-compose.free.yml logs -f --tail=100"
echo "  Update: git pull && docker compose -f docker-compose.free.yml up -d --build"
echo ""
echo "  Not loading? Add Ingress TCP/80 in OCI Console (VCN > Security List)."
echo "════════════════════════════════════════════════════════════"
