"""
G1: Reset paper-trading baseline to ZERO.

Why: before the G1 rewire, every trade in `arb:orders` was generated by a
random emitter with a random.choice() strategy label. That history is fiction
and cannot be attributed. Run this ONCE after deploying the signal-driven
engine so the honest baseline starts clean.

Clears:
  - arb:orders            (the trade ledger the dashboard rebuilds PnL from)
  - arb:signals           (stale random-labeled signals)
  - arb:risk:* daily-loss counters

Safe to run repeatedly. Does NOT touch wallet links or market data.

Usage (on VPS):
  docker exec reyog_engine python scripts/reset_paper_baseline.py
"""
import asyncio
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from arb.infra.redis_bus import get_redis, close_redis

CLEAR_KEYS = [
    "arb:orders", "arb:signals",
    # Polymarket paper state — clear for a fully clean real-data run
    "arb:polymarket:bets", "arb:poly:resolved", "arb:risk:halted",
]
CLEAR_PATTERNS = [
    "arb:risk:polymarket_daily_loss:*", "arb:risk:daily_loss:*",
    "arb:poly:seen:*",     # let engine re-bet markets fresh
    "arb:poly:stats:*",    # reset per-asset win/loss hit-rate
]


async def main() -> None:
    r = get_redis()
    report = {}

    for key in CLEAR_KEYS:
        # Key may be a list, set, or string — delete works for all types.
        try:
            ktype = await r.type(key)
        except Exception:
            ktype = "?"
        await r.delete(key)
        report[key] = f"deleted (type={ktype})"

    for pat in CLEAR_PATTERNS:
        keys = [k async for k in r.scan_iter(match=pat)]
        if keys:
            await r.delete(*keys)
        report[pat] = f"deleted ({len(keys)} keys)"

    print("=== G1 paper baseline reset ===")
    for k, v in report.items():
        print(f"  {k}: {v}")
    print("Honest baseline starts now. Let it run >=24h before reading G1.2.")

    await close_redis()


if __name__ == "__main__":
    asyncio.run(main())
